run:
  timeout: 10m
  # Enable checking the by default skipped "examples" dirs
  skip-dirs:
    - vendor$
    - third_party$
    - testdata$
    - Godeps$
    - builtin$
  skip-dirs-use-default: false
linters:
  enable-all: false
  enable:
    # - durationcheck
    - errcheck
    - goconst
    - gofmt
    # - goprintffuncname
    - gomnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    # - nilnil
    - paralleltest
    # - prealloc
    # - predeclared
    - revive
    - structcheck
    # - tenv
    # - thelper
    - unconvert
    # - unparam
    - unused
    - varcheck
    # - wastedassign
    # - whitespace
    # - wrapcheck
  disable:
    - staticcheck # Disabled due to OOM errors in golangci-lint@v1.18.0
    - megacheck # Disabled due to OOM errors in golangci-lint@v1.18.0
