name: Goreleaser Prep

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      ref:
        required: true
        description: "GitHub ref to use"
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: common
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Set up bin dir
        run: ./scripts/prep-for-goreleaser.sh
      - name: Show files and permissions
        run: find bin -type f -printf "%M    %p/"\\n
      - uses: actions/upload-artifact@v2
        with:
          name: build-external-deps
          retention-days: 1
          path: ./bin/*
