name: Issue management

on:
  schedule:
  - cron: '12 13 * * *'

jobs:
  stale:
    name: Close stale awaiting-feedback issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@5ebf00ea0e4c1561e9b43a292ed34424fb1d4578 // v6.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        any-of-labels:
          - awaiting-feedback
          - awaiting-feedback-stale
        stale-issue-message: 'Since we haven''t heard back from you, closing this issue for now. Please feel free to comment with more information and we can get this reopened.'
        stale-issue-label: awaiting-feedback-stale
        days-before-stale: 14
        labels-to-add-when-unstale: needs-triage
